name: "pre-release"
run-name: "Pre-releasing ${{ github.ref }}"
on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Create Pre-release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Composer install"
        run: "composer install"
      - name: "Box application"
        run: "vendor/bin/box compile"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            bin/*
